name: gww
channels:
  - conda-forge
dependencies:
  - pip
  - python=3.7
  - geopandas
  - matplotlib
  - numpy
  - pandas
  - requests
  - cartopy 
  - tqdm
  - scipy
  - shapely
  - ipykernel
  - pip:
    